title: Jobenko
email: joelkbennett@gmail.com
description: >
  Recent work by Vancouver<br> based Web Developer <strong>Joel Bennett</strong>
baseurl: "" 
url: "https://jobenko.com"
twitter_username: j0benk0
github_username:  joelkbennett
markdown: kramdown
destination:  ./dist
