title: Jobenko
email: joelkbennett@gmail.com
description: >
  Recent work, words and sketches by Vancouver<br> based Front-End Developer &amp; Graphic Designer<br><strong>Joel K Bennett</strong>
baseurl: "" 
url: "https://jobenko.com"
twitter_username: j0benk0
github_username:  joelkbennett
markdown: kramdown
destination:  ./dist
